### ISSUE TITLE
Docker image takes up too much space

### ISSUE THREAD

**Issue by Qetesh** [tarioch/docker-fava#129]
The image size is over 800 MB, consuming excessive space and taking up too much time when updating.

btw, Thank you very much for creating such a ready-to-use container image.

**Comment by tarioch** [comment]
I now don't cache the pip packages anymore, this might help a little bit. Otherwise unfortunately I don't see much room for improvement, I have some pretty big stuff in there (scikit stuff for smart-importer and some other stuff for being able to extract out of pdf).
The base python container which I'm using is already around 300MB and I need that one for some of the installation.
